### ISSUE TITLE
notifications and unclear error

### ISSUE THREAD

**Issue by jakejh** [DevDataPlatform/DDP_backend#295] opened 2023-08-23 16:15 UTC
- Is there a way to get email notifications of the results of orchestration runs?
- The last couple runs of my flow have failed and it's not clear why.
- The last successful run of my active orchestration flow was a couple days ago, but the "last sync" in the ingest tab was still showing "6 days ago".

**Comment by fatchat** [comment] 2023-08-23 16:29
1. not right now, we have written a prefect plugin which sends emails when runs finish, but the address to which they send is hardcoded into the plugin's settings. my eventual plan is to make a plugin which notifies the upstream dalgo system which will then look up the account's users and email them

2. i saw those... the "read timed out" messages right? we saw those as well even though the airbyte syncs completed successfully. don't have an answer yet

3. we are "fixing" this to clarify that the last sync in the ingest tab is the last manual sync. we will make a proper fix next month

**Comment by jakejh** [comment] 2023-08-23 16:32
Cool, you're on it.

**Comment by fatchat** [comment] 2023-08-26 18:11
ii. this was caused by a 5 second timeout when prefect initiates an airbyte sync via the `/v1/connections/sync` api. that api returns a `job_id` using which prefect checks on the progress... without the `job_id` prefect is blind so it really needs it

for some reason this request doesn't always finish in 5 seconds although airbyte queues and runs the job just fine

i have increased the timeout to 15 seconds (!) which should be more than enough. if we see this issue again i will look at why airbyte is taking so long

**Comment by fatchat** [comment] 2023-08-27 01:48
linking & closing
1. https://github.com/DevDataPlatform/DDP_backend/issues/298
2. https://github.com/DevDataPlatform/prefect-proxy/pull/73
3. https://github.com/DevDataPlatform/webapp/issues/307

**Closed by fatchat** 2023-08-27 01:48 UTC
